### ISSUE TITLE
[frontend][backend] deciding request and response format for Image

### ISSUE THREAD

**Issue by ByungHeeCha** [swsnu/swpp2019-team10#12]
I searched various ways to handle image for REST api. I think we can consider 3 methods in this link.
[https://stackoverflow.com/questions/33279153/rest-api-file-ie-images-processing-best-practices](url)
I think many people liked second one. What do you think?

**Comment by jyeok** [comment]
it seems that link is crashed: [click here](https://stackoverflow.com/questions/33279153/rest-api-file-ie-images-processing-best-practices)

I think second way is good, in terms of user experience.
