### ISSUE TITLE
Sprint 3 Meeting

### ISSUE THREAD

**Issue by JaehoNam** [swsnu/swpp2019-team10#4]
Let's fix the sprint 3 meeting time!!

https://docs.google.com/spreadsheets/d/127ZvDVj-YY3h0NMyTG9IcsT0uqozuDj_Axdos2eqhTw/edit?usp=sharing

저는 빈 시간 중에서는 목요일 오전이나 금요일 5시 이후만 가능합니다..

**Comment by ByungHeeCha** [comment]
Both are okay to me!

**Comment by jyeok** [comment]
Me too, but i prefer friday 5 pm.

**Comment by ktaebum** [comment]
그래서 금요일에 하시나요?ㅋㅋ

**Comment by ByungHeeCha** [comment]
금요일 5시로 하겠습니다!
