### ISSUE TITLE
[Todo] Until Tomorrow

### ISSUE THREAD

**Issue by jyeok** [swsnu/swpp2019-team10#48]
Let's talk about our TODOs until tomorrow 6 P.M.
If clarification or discussion is requird, let's talk here together!

**Comment by th-snu** [comment]
I'll check if review part I implemented has more issues, and fix them. And I'll implement google map view on AddReview and ReviewDetail.

**Comment by jyeok** [comment]
I'll implement today [mock view of recommendation system](https://github.com/swsnu/swpp2019-team10/wiki/Design-and-Implementation) accroding to our wiki document.

As I know, @JaehoNam is going to handle tag-parsing, I'd like to request you to send a tag data as the form of [ { name: 'Tagname1', sentimental: {-1/0/1} ] !
