### ISSUE TITLE
About Map API

### ISSUE THREAD

**Issue by jyeok** [swsnu/swpp2019-team10#5]
According to [our design and implmentation wiki](https://github.com/swsnu/swpp2019-team10/wiki/Design-and-Implementation), We are to use [django-location-field](https://github.com/caioariede/django-location-field) and [KaKao Map API](http://apis.map.kakao.com/web/guide/).

But `django-location-field` seems to not supporting the KaKaoMap but Google Map. So if we are to use `django-location-field` , I think we have to change our location/search provider to Google Map.

I Think Google Map is better since our service is based on English except the name of menu and Our Sign in with SNS will support Google Login. What you guys think about it?

**Comment by ByungHeeCha** [comment]
I wonder what does google map support for google users.

**Comment by ByungHeeCha** [comment]
I think it will be easier using google map api then kakao api. However, I think google map doesn't have much information than kakao map in Korea.

**Comment by jyeok** [comment]
Although we don’t use particular feature of google maps, user will feel awkward if our service supports many google-based features (log-in with google, google calender, uploading picture via google image/drive etc..) but uses KaKao Map for only map feature. Because we are going to use special features which kakomap api provides, I think it is matter of inconsistency. Windows 10용 메일에서 보냄 보낸 사람: ByungHeeCha보낸 날짜: 2019년 10월 27일 일요일 오후 3:25받는 사람: swsnu/swpp2019-team10참조: jyeokchoi; Author제목: Re: [swsnu/swpp2019-team10] About Map API (#5) I wonder what does google map support for google users.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ByungHeeCha** [comment]
???

**Comment by jyeok** [comment]
FYI when typing ‘우참순’ to each Map service, Google map automatically redirects to ‘우리가참순대’ but Kakao Map gives no results. Also, google map has far more data that seems useful. When we type ‘박막례청진동해장국’, google map shows 347 reviews and ‘relevant location’, kakao map shows shows only 15 reviews with ‘daum blog review’. Maybe no need to worrying about lack of location / information using google map

**Comment by ByungHeeCha** [comment]
Hmm... well google map was better than I thought!

**Comment by th-snu** [comment]
as we're to integrate google service in many of our services, consistently using google map api would help our development too imo

**Comment by jyeok** [comment]
It seems cofirmed that we are going to use Google Map API instaed of KaKao Map, So I'll close this issue.
