### ISSUE TITLE
[backend] make backend views for review in review_views.py

### ISSUE THREAD

**Issue by ByungHeeCha** [swsnu/swpp2019-team10#6]
Will implement review_list and review_detail

**Comment by JaehoNam** [comment]
Writing the code related to friend feature, I realized that we also need api to call the review list and detail with friend_id. So I think we need to add

| Model | API | GET | POST | PUT | DELETE |
| :--- | :--- | :--- | :--- | :--- | :--- |
| Review | ``` api/friend/:friend_id/review ``` | Get friend's review list | X | X | X |
| | ``` api/friend/:friend_id/review/:review_id ``` | Get friend's specified review | X | X | X |

How about?

**Comment by ByungHeeCha** [comment]
OK. I'll implement this too.

**Comment by JaehoNam** [comment]
https://stackoverflow.com/questions/44714046/python3-unable-to-import-jsondecodeerror-from-json-decoder

I have had a problem with importing ```JSONDecodeError``` because our program runs on travis CI with python version=3.4.8. So I think we need to change this to ```ValueError``` or change travis.yml setting.

**Comment by ByungHeeCha** [comment]
Let's change travis.yml setting. Then we will resolve JSONDecodeError problem.

**Comment by JaehoNam** [comment]
I have changed our travis.yml python version setting to >=3.5 and our travis on backend branch success..!!ㅠㅠㅠ
