### ISSUE TITLE
[setting] python version

### ISSUE THREAD

**Issue by JaehoNam** [swsnu/swpp2019-team10#9]
Please leave a comment below about your **python version**
(The number when you type ```python --version``` in the console)

I need this for writing backend code..

**Comment by JaehoNam** [comment]
Python 3.7.4

**Comment by ByungHeeCha** [comment]
Please comment your problem on issue #6 

My python version is Python 3.7.3

**Comment by th-snu** [comment]
I'm using Python 3.7.0

**Comment by ByungHeeCha** [comment]
His issue is in https://github.com/swsnu/swpp2019-team10/issues/6#issuecomment-547715352

**Comment by jyeok** [comment]
python 3.6.8

**Comment by jyeok** [comment]
Refering to comment of [issue #6](https://github.com/swsnu/swpp2019-team10/issues/6) I think this bug is now solved, so I'll close this issue.
